import {Client} from './client';

export const CLIENTS: Client[] = [

  {
    id: 1,
    name: "Paul",
    propertyAddress: "4424 Stoneyglen",
    propertyCity: "Moorpark",
    propertyState: "Ca",
    askingPrice: 430000,
    phoneNumber: "805 990 4692",
    emailAddress: "mcharnock@gmail.com",
    teamMember: "Tim Levowski",
  },

  {
    id: 2,
    name: "Chris",
    propertyAddress: "123 Wayglen",
    propertyCity: "Simi Valley",
    propertyState: "Ca",
    askingPrice: 240000,
    phoneNumber: "805 212 4692",
    emailAddress: "mcharnock@gmail.com",
    teamMember: "Paul Goldy",
  },

  {
    id: 3,
    name: "Paul",
    propertyAddress: "4424 Stoneyglen",
    propertyCity: "Moorpark",
    propertyState: "Ca",
    askingPrice: 430000,
    phoneNumber: "805 990 4692",
    emailAddress: "mcharnock@gmail.com",
    teamMember: "Tim Levowski",
  },
  {
    id: 4,
    name: "Jake",
    propertyAddress: "4424 Stoneyglen",
    propertyCity: "Moorpark",
    propertyState: "Ca",
    askingPrice: 5600000,
    phoneNumber: "805 990 4692",
    emailAddress: "mcharnock@gmail.com",
    teamMember: "Ted Navel",
  },
  {
    id: 5,
    name: "Schmidt",
    propertyAddress: "4424 Powerbrook",
    propertyCity: "Westlake",
    propertyState: "Ca",
    askingPrice: 4000000,
    phoneNumber: "805 211 4692",
    emailAddress: "mcharnock@gmail.com",
    teamMember: "Craig Lavinski",
  },
  {
    id: 6,
    name: "Tim",
    propertyAddress: "2343 Glenstreet",
    propertyCity: "Moorpark",
    propertyState: "Ca",
    askingPrice: 430000,
    phoneNumber: "805 907 4692",
    emailAddress: "mcharnock@gmail.com",
    teamMember: "Tim Levowski",
  },
  {
    id: 7,
    name: "Paul",
    propertyAddress: "4424 Stoneyglen",
    propertyCity: "Moorpark",
    propertyState: "Ca",
    askingPrice: 430000,
    phoneNumber: "805 990 4692",
    emailAddress: "mcharnock@gmail.com",
    teamMember: "Tim Levowski",
  },

  {
    id: 8,
    name: "Chris",
    propertyAddress: "123 Wayglen",
    propertyCity: "Simi Valley",
    propertyState: "Ca",
    askingPrice: 240000,
    phoneNumber: "805 212 4692",
    emailAddress: "mcharnock@gmail.com",
    teamMember: "Paul Goldy",
  },

  {
    id: 9,
    name: "Paul",
    propertyAddress: "4424 Stoneyglen",
    propertyCity: "Moorpark",
    propertyState: "Ca",
    askingPrice: 430000,
    phoneNumber: "805 990 4692",
    emailAddress: "mcharnock@gmail.com",
    teamMember: "Tim Levowski",
  },
  {
    id: 10,
    name: "Jake",
    propertyAddress: "4424 Stoneyglen",
    propertyCity: "Moorpark",
    propertyState: "Ca",
    askingPrice: 5600000,
    phoneNumber: "805 990 4692",
    emailAddress: "mcharnock@gmail.com",
    teamMember: "Ted Navel",
  },
  {
    id: 11,
    name: "Schmidt",
    propertyAddress: "4424 Powerbrook",
    propertyCity: "Westlake",
    propertyState: "Ca",
    askingPrice: 4000000,
    phoneNumber: "805 211 4692",
    emailAddress: "mcharnock@gmail.com",
    teamMember: "Craig Lavinski",
  },
  {
    id: 12,
    name: "Tim",
    propertyAddress: "2343 Glenstreet",
    propertyCity: "Moorpark",
    propertyState: "Ca",
    askingPrice: 430000,
    phoneNumber: "805 907 4692",
    emailAddress: "mcharnock@gmail.com",
    teamMember: "Tim Levowski",
  },
]
